stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Hello, build!"

test:
  stage: test
  script:
    - echo "Hello, test!"

deploy:
  stage: deploy
  script:
    - echo "Hello, deploy!"
