stages:
  - name: build
    jobs:
      - name: build
        script:
          - echo "Hello, build!"

  - name: test
    jobs:
      - name: test
        script:
          - echo "Hello, test!"

  - name: deploy
    jobs: 
      - name: deploy
        script:
          - echo "Hello, deploy!"
